package com.dafeng.upgradeapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOM_APP.
 */
public class CustomApp {

    private Long id;
    /** Not-null value. */
    private String packageName;

    public CustomApp() {
    }

    public CustomApp(Long id) {
        this.id = id;
    }

    public CustomApp(Long id, String packageName) {
        this.id = id;
        this.packageName = packageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPackageName() {
        return packageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

}
