package com.dafeng.upgradeapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dafeng.upgradeapp.dao.CustomApp;

import com.dafeng.upgradeapp.dao.CustomAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customAppDaoConfig;

    private final CustomAppDao customAppDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customAppDaoConfig = daoConfigMap.get(CustomAppDao.class).clone();
        customAppDaoConfig.initIdentityScope(type);

        customAppDao = new CustomAppDao(customAppDaoConfig, this);

        registerDao(CustomApp.class, customAppDao);
    }
    
    public void clear() {
        customAppDaoConfig.getIdentityScope().clear();
    }

    public CustomAppDao getCustomAppDao() {
        return customAppDao;
    }

}
